import {
    ShoppingBag,
    ShoppingCart,
    Search,
    User,
    Heart,
    Menu,
    X,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    ChevronUp,
    Phone,
    Mail,
    MapPin,
    Star,
    Filter,
    SlidersHorizontal,
    Plus,
    Minus,
    Trash2,
    Check,
    Eye,
    EyeOff,
    CreditCard,
    Truck,
    ShieldCheck,
    Tag,
    LayoutDashboard,
    Package,
    Users,
    ClipboardList,
    TrendingUp,
    DollarSign,
    Edit,
    Download,
    Upload,
    Printer,
    RotateCw,
    LogOut,
    Settings,
    MoreVertical,
    AlertCircle,
    Sparkles,
    Headphones
} from "lucide-react";

export const Icons = {
    shoppingBag: ShoppingBag,
    shoppingCart: ShoppingCart,
    search: Search,
    user: User,
    heart: Heart,
    menu: Menu,
    close: X,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronUp: ChevronUp,
    phone: Phone,
    mail: Mail,
    mapPin: MapPin,
    star: Star,
    filter: Filter,
    sliders: SlidersHorizontal,
    plus: Plus,
    minus: Minus,
    trash: Trash2,
    check: Check,
    eye: Eye,
    eyeOff: EyeOff,
    creditCard: CreditCard,
    truck: Truck,
    shieldCheck: ShieldCheck,
    tag: Tag,
    dashboard: LayoutDashboard,
    products: Package,
    customers: Users,
    orders: ClipboardList,
    analytics: TrendingUp,
    revenue: DollarSign,
    edit: Edit,
    download: Download,
    upload: Upload,
    print: Printer,
    refresh: RotateCw,
    logout: LogOut,
    settings: Settings,
    more: MoreVertical,
    alert: AlertCircle,
    sparkles: Sparkles,
    headphones: Headphones,
    
};

export type IconType = keyof typeof Icons;